### ISSUE TITLE
Undefined "includeInvisible" when using "type: hacd;"

### ISSUE THREAD

**Issue by alexthake** [c-frame/aframe-physics-system#31] opened 2023-02-20 18:18 UTC
Trying to use the `hacd` Ammo shape type with the Ammo Driver.
The following console error comes up:

Uncaught TypeError: Cannot read properties of undefined (reading 'includeInvisible')
    at aframe-physics-system.min.js:1:214940
    at Mesh.traverse (three.js:5985:1)
    at aframe-physics-system.min.js:1:214852
    at aframe-physics-system.min.js:1:216333
    at Object.createHACDShapes (aframe-physics-system.min.js:1:205034)
    at exports.createCollisionShapes (aframe-physics-system.min.js:1:199846)
    at i._createCollisionShape (aframe-physics-system.min.js:1:247486)
    at i.<anonymous> (aframe-physics-system.min.js:1:246580)
    at i.beforeStep (aframe-physics-system.min.js:1:250305)
    at o.tick (aframe-physics-system.min.js:1:289954)

Issue does not occur prior to version 4.1.0, but those versions have their own fun quirks

**Comment by diarmidmackenzie** [comment] 2023-06-26 13:20
This is easily reproduced by uncommenting this entity in the ammo sandbox example:

```
      <a-torus-knot
        position="-2 1.5 -1"
        rotation="0 90 90"
        scale="0.5 0.5 0.5"
        color="red"
        shadow
        ammo-body
        ammo-shape="type: hacd;"
      ></a-torus-knot>
```

The problem appears to be that this line of code in three-to-ammo does not pass on `options` object to `computeBounds()`

```
const bounds = _computeBounds(root);
```

Fixing it like this seems to make HACD work again
```
const bounds = _computeBounds(root, options);
```

I am puzzled how this used to work at 4.1.0...

We are still using three-to-ammo 0.1.0 (plus some patches) and there are some substantial interface changes blocking us from moving to 1.0.1.  So best solution is probably to patch three-to-ammo using npm-patch-package, [as we have done before...](https://github.com/c-frame/aframe-physics-system/pull/21)

Before I submit that PR, I'd like to dig a bit more into how this worked at 4.1.0...

**Comment by diarmidmackenzie** [comment] 2023-06-26 15:00
So the problematic line was introduced with this checkin:
https://github.com/InfiniteLee/three-to-ammo/commit/5b0587c660080822049f1ed87e13ba15f0e74d2f

and it looks like a straightforward oversight that `options` was not passed as an additional parameter on the call to _computeBounds()

Only versions of aframe-physics-system I can find with HACD working predate this change to three-to-ammo (v4.0.1).

Contrary to note above, 4.1.0 seems to have the same issue.

Tracking down specific details on when we switched from one version of three-to-ammo to another is hard, as prior to [this point](https://github.com/c-frame/aframe-physics-system/commit/f312a2a990008b224d9e02a5ea78b5d0f9d32ccc), aframe-physics-system just built off the latest github...

**Comment by diarmidmackenzie** [comment] 2023-10-11 18:42
master is now using three-to-ammo 1.0.1, and HACD seems to be working fine.

**Closed by diarmidmackenzie** 2023-10-11 18:42 UTC
